services:
  # backend:
  #   build: ./back
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - 8080:8080
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #     placement:
  #       constraints: [node.role != manager]

  # proxy:
  #   image: nginx:stable
  #   restart: always
  #   depends_on:
  #     - backend
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./back/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   deploy:
  #     mode: replicated
  #     replicas: 2
  #     labels: [TESTE=IVRIM]
  #     restart_policy:
  #       condition: on-failure
  #     placement:
  #       constraints: [node.role != manager]

  db:
    image: postgres
    restart: always
    env_file:
      - ./back/.env
    ports:
      - 5432:5432
    volumes:
      - ./data:/lib/postgres/data
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    #   placement:
    #     constraints: [node.role != manager]